#pragma once
#include <string>
#include <GL\glew.h>
#include <GL\GLU.h>
#include <GL\glut.h>
#include "src\objects\PlayerObject.h"
#include "src\objects\CircleObject.h"
#include "src\graphics\Window.h"
#include "src\Input\InputController.h"
#include "src\motion\MotionController.h"
#include <stdlib.h>